
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Sep 18 2024 14:40:26 IST (Sep 18 2024 09:10:26 UTC)

// Verification Directory fv/csa 

module fa(a, b, c, s, co);
  input a, b, c;
  output s, co;
  wire a, b, c;
  wire s, co;
  ADDFX1 g52(.A (a), .B (b), .CI (c), .CO (co), .S (s));
endmodule

module fa_12(a, b, c, s, co);
  input a, b, c;
  output s, co;
  wire a, b, c;
  wire s, co;
  ADDFX1 g52(.A (a), .B (b), .CI (c), .CO (co), .S (s));
endmodule

module fa_11(a, b, c, s, co);
  input a, b, c;
  output s, co;
  wire a, b, c;
  wire s, co;
  ADDFX1 g52(.A (a), .B (b), .CI (c), .CO (co), .S (s));
endmodule

module fa_10(a, b, c, s, co);
  input a, b, c;
  output s, co;
  wire a, b, c;
  wire s, co;
  ADDFX1 g52(.A (a), .B (b), .CI (c), .CO (co), .S (s));
endmodule

module fa_7_13(a, b, c, s, co);
  input a, b, c;
  output s, co;
  wire a, b, c;
  wire s, co;
  ADDHX1 g19(.A (a), .B (b), .CO (co), .S (s));
endmodule

module fa_9(a, b, c, s, co);
  input a, b, c;
  output s, co;
  wire a, b, c;
  wire s, co;
  ADDFX1 g52(.A (a), .B (b), .CI (c), .CO (co), .S (s));
endmodule

module fa_8(a, b, c, s, co);
  input a, b, c;
  output s, co;
  wire a, b, c;
  wire s, co;
  ADDFX1 g52(.A (a), .B (b), .CI (c), .CO (co), .S (s));
endmodule

module fa_7(a, b, c, s, co);
  input a, b, c;
  output s, co;
  wire a, b, c;
  wire s, co;
  CLKXOR2X1 g10(.A (a), .B (b), .Y (s));
endmodule

module csa(a, b, c, S, clk);
  input [3:0] a, b, c;
  input clk;
  output [4:0] S;
  wire [3:0] a, b, c;
  wire clk;
  wire [4:0] S;
  wire [4:0] s;
  wire [10:0] w;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0;
  fa y1(a[0], b[0], c[0], s[0], w[0]);
  fa_12 y2(a[1], b[1], c[1], w[1], w[2]);
  fa_11 y3(a[2], b[2], c[2], w[3], w[4]);
  fa_10 y4(a[3], b[3], c[3], w[5], w[6]);
  fa_7_13 y5(w[0], w[1], UNCONNECTED_HIER_Z, s[1], w[7]);
  fa_9 y6(w[2], w[3], w[7], s[2], w[8]);
  fa_8 y7(w[4], w[5], w[8], s[3], w[9]);
  fa_7 y8(w[6], w[9], UNCONNECTED_HIER_Z0, s[4], w[10]);
  DFFHQX1 \S_reg[4] (.CK (clk), .D (s[4]), .Q (S[4]));
  DFFHQX1 \S_reg[3] (.CK (clk), .D (s[3]), .Q (S[3]));
  DFFHQX1 \S_reg[2] (.CK (clk), .D (s[2]), .Q (S[2]));
  DFFHQX1 \S_reg[1] (.CK (clk), .D (s[1]), .Q (S[1]));
  DFFHQX1 \S_reg[0] (.CK (clk), .D (s[0]), .Q (S[0]));
endmodule

